version: '3.8'
services:
    frontend:
        build: .
        restart: always
        expose:
         - '80'
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.random-frontend.entrypoints=web"
          - "traefik.http.routers.random-frontend.rule=Host(`random.random.com`)"
          - "traefik.http.routers.random-frontend.middlewares=redirect-to-https@docker"
          - "traefik.http.routers.random-frontend-secure.entrypoints=websecure"
          - "traefik.http.routers.random-frontend-secure.rule=Host(`random.random.com`)"
          - "traefik.http.routers.random-frontend-secure.tls=true"
          - "traefik.http.routers.random-frontend-secure.tls.certresolver=letsencryptresolver"
          - "traefik.http.services.random-frontend.loadbalancer.server.port=80"
          - "traefik.docker.network=traefik"
        networks:
          - traefik
networks:
  traefik:
    external: true
